sudo: required
dist: trusty
branches:
  only:
  - master
  - dev
env:
  global:
  - PROJECT_NAME=fake-shop
  - ORG=madiedinro
  - IMAGE_NAME=$ORG/$PROJECT_NAME
  - TAG="$( [ $TRAVIS_BRANCH == 'master' ] && echo latest || echo $TRAVIS_BRANCH )"
  - secure: W7oDUtr1AYD0NbL4ik4iol1OGfsRD+jn6w6iOieJXNk5CpfE3Mx68Q2InKoDKM0nut8f/T9hy5qQtqtCQUDACAnMFlfIt6KbsB0gAIMFwXsnx68CSxpo6rd+IuWGOBtX/ZFyQeJIhJcZfrwOUOcq8N0+6KNHfA4jsTQ1sfb/R6PuxZ4rEDxIeSExNhlyckE4YH5ssbdSsY7lOznYiIX9ExfzS6O3yvBkCEy1QKyQ17oT9V/b1LN8o5CxhYXfJvpDFYprdlrs/kKg/kiR5R1x5oHb1xrI5onWDJQUMCW7+ftzZqiyALsG5YkuVtpyUzzU4T6fu+JOofwcju5n4opucC+nh2SSICb5pJBx9BRNg7r73POhtmgzCigS2TKilW6kVVGxYAVqbTNRHZc8wju5z5Ij786F7R8kS2mPte5bUXRlutgz+OHGQtKXM6mIwLk8zZ7HiW5DHFEZmuTXqy68gYqlhfn1yy57OeV/vHTMqBfpGEUeE9l1FnNJ4rySVI9J8UMJ3Ib4n9pULexd0YAeSqqVSYURGnUlcAEMs62ehvv/icGntAqpDxZ+n2VsK4/0x5DjiJ+tad4P1LFcXLOkiEnBfFHqJ27VVrMey+nvbajXtSPUlbkrfLQzDy4T3budaigdS5t3x8BZ9sjHr8Rirg/PFPcjsRVMk/u/xb0gdlA=
services:
- docker
script:
- cat Dockerfile | sed  "s/\:latest/\:$TAG/g" > Dockerfile.tag
- docker build -t $PROJECT_NAME -f Dockerfile.tag .
after_script:
- docker images
before_deploy:
- docker tag "$PROJECT_NAME" "$IMAGE_NAME:$TAG"
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
  provider: script
  skip_cleanup: true
  script: docker push "$IMAGE_NAME:$TAG"
  on:
    all_branches: true
